In [1]:
# 두개 이상의 열을 가지는 데이터 프레임
# 딕셔너리를 데이터 프레임으로 변환
# pandas.DataFrame(딕셔너리)

import pandas as pd

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

# 시리즈로 변환
sr = pd.Series(dict_data)
print(sr)

# 데이터프레임으로 변환
df = pd.DataFrame(dict_data)
print(df)

c0       [1, 2, 3]
c1       [4, 5, 6]
c2       [7, 8, 9]
c3    [10, 11, 12]
c4    [13, 14, 15]
dtype: object
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [2]:
print(type(df))

<class 'pandas.DataFrame'>

In [3]:
# 행 인덱스 / 열 이름 설정

import pandas as pd

list_data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(list_data, index=["준서", "예은"], columns=["나이", "성별", "학교"])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [4]:
# 인덱스 명 가져오기

print(df.index)

Index(['준서', '예은'], dtype='str')

In [5]:
# 열 이름 가져오기

print(df.columns)

Index(['나이', '성별', '학교'], dtype='str')

In [6]:
# 인덱스 명과 열 이름 변경하기

df.index = ["학생1", "학생2"]
df.columns = ["연령", "남녀", "소속"]

print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [7]:
list_data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(list_data, index=["준서", "예은"], columns=["나이", "성별", "학교"])

In [8]:
df = df.rename(columns={
    "나이" : "연령",
    "성별" : "남녀",
    "학교" : "소속"
})

print(df)

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [9]:
df = df.rename(index={
    "준서" : "학생1",
    "예은" : "학생2"
})

print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [10]:
# 행 / 열 삭제

# 행 삭제 -> DataFrame객체.drop(행인덱스 또는 배열, axis = 0 또는 axis = "index")
# 열 삭제 -> DataFrame객체.drop(열이름 또는 배열, axis = 1 또는 axis = "columns")

In [11]:
import pandas as pd

exam_data = {
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "인아"])
print(df)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [12]:
df2 = df.copy()
print(df2)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [13]:
df2 = df2.drop("우현")  # axix = 0 (default)
print(df2)

    수학  영어   음악   체육
서준  90  98   95  100
인아  70  95  100   90

In [14]:
df3 = df.copy()
print(df3)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [15]:
df3 = df3.drop("영어", axis=1)
print(df3)

    수학   음악   체육
서준  90   95  100
우현  80   95   90
인아  70  100   90

In [16]:
df3 = df.copy()
print(df3)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [17]:
df3 = df3.drop(["영어", "음악"], axis=1)
print(df3)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [18]:
df4 = df.copy()
print(df4)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [19]:
df4 = df4.drop(["수학", "체육"], axis="columns")
print(df4)

    영어   음악
서준  98   95
우현  89   95
인아  95  100

In [20]:
df5 = df.copy()
df5 = df5.drop(columns=["수학", "영어"])
print(df5)

     음악   체육
서준   95  100
우현   95   90
인아  100   90

In [21]:
# 행선택
# loc 인덱서

df6 = df.copy()

# print(df6.loc["서준"])
label1 = df6.loc["서준"]
position1 = df6.iloc[0]

print(label1)
print()
print(position1)

수학     90
영어     98
음악     95
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     95
체육    100
Name: 서준, dtype: int64

In [22]:
label2 = df.loc[["서준", "우현"]]
position2 = df.iloc[[0, 1]]

print(label2)
print()
print(position2)

    수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90

In [23]:
# 열선택

import pandas as pd

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
print(df)
print(type(df))

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90
<class 'pandas.DataFrame'>

In [24]:
# df["수학"] -> Series 타입
math1 = df["수학"]

In [25]:
print(df.영어)
print(type(df.영어))

0    98
1    89
2    95
Name: 영어, dtype: int64
<class 'pandas.Series'>

In [26]:
music_gym = df[["음악", "체육"]]
print(music_gym)
print(type(music_gym))

    음악   체육
0   95  100
1   95   90
2  100   90
<class 'pandas.DataFrame'>

In [27]:
math1 = df['수학']
math2 = df[['수학']]

print(math1)
print(type(math1))
print()
print(math2)
print(type(math2))

0    90
1    80
2    70
Name: 수학, dtype: int64
<class 'pandas.Series'>

   수학
0  90
1  80
2  70
<class 'pandas.DataFrame'>

In [28]:
# iloc 을 이용한 범위 슬라이싱
# 데이터프레임객체.iloc[시작인덱스 : 끝인덱스 : 간격]

print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [29]:
print(df.iloc[0])

이름     서준
수학     90
영어     98
음악     95
체육    100
Name: 0, dtype: object

In [30]:
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
2  인아  70  95  100   90

In [31]:
df[0:2]

   이름  수학  영어  음악   체육
0  서준  90  98  95  100
1  우현  80  89  95   90

In [32]:
df[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
2  인아  70  95  100   90

In [33]:
df[:3]

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [34]:
df[1::1]

   이름  수학  영어   음악  체육
1  우현  80  89   95  90
2  인아  70  95  100  90

In [35]:
df.iloc[::-1]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   95  100

In [36]:
# 원소 선택

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix[1][1]

5

In [37]:
exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [38]:
# 인덱스이름: DF객체.loc[행인덱스, 열이름]
# 정수위치인덱스: DF객체.iloc[행번호, 열번호]

print(df.loc["서준", "음악"])
print(df.iloc[0, 2])

95
95

In [39]:
# 열 추가
# DF객체["추가하려는 열 이름"] = 데이터 값

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df["국어"] = 80
df["미술"] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   95  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [40]:
# 행 추가
# DF객체.loc["추가할 행 이름"] = 데이터 값 또는 배열

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df.loc[3] = 0
df.loc[4] = ["동규", 90, 80, 70, 60]
df.loc["행5"] = df.loc[1]
df.loc["행6"] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   95  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5  우현  80  89   95   90
행6   0   0   0    0    0

In [41]:
# 원소 값 변경

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df = df.set_index("이름")
print(df)
print()
df.iloc[0, 3] = 95
df.loc["서준", "체육"] = 90
print(df)

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

    수학  영어   음악  체육
이름
서준  90  98   95  90
우현  80  89   95  90
인아  70  95  100  90

In [42]:
print(df.iloc[0].iloc[3])
print(df.iloc[0]["체육"])
print(df.loc["서준"]["체육"])

90
90
90

In [43]:
# 행과 열의 위치 바꾸기
# DF객체.transpose()
# DF객체.T

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)

df = df.transpose()
print(df)
print()

df = df.T
print(df)

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   95  95  100
체육  100  90   90

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90