In [1]:
import pandas as pd

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
print(df.ndim)
print(df.shape)

2
(3, 5)

In [2]:
ndf = df.set_index("이름")
ndf

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [3]:
print(ndf.shape)

(3, 4)

In [4]:
ndf2 = ndf.set_index("음악")
ndf2

     수학  영어   체육
음악
95   90  98  100
95   80  89   90
100  70  95   90

In [5]:
ndf3 = ndf.set_index(["수학", "음악"])
ndf3

        영어   체육
수학 음악
90 95   98  100
80 95   89   90
70 100  95   90

In [6]:
# 행인덱스 재배열

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=["r0", "r1", "r2"])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [7]:
new_index = ["r0", "r1", "r2", "r3", "r4"]
ndf = df.reindex(new_index)
ndf

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [8]:
ndf.loc["r3"]

c0   NaN
c1   NaN
c2   NaN
c3   NaN
c4   NaN
Name: r3, dtype: float64

In [9]:
ndf2 = df.reindex(new_index, fill_value=0)
ndf2

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [10]:
ndf2["c0"]

r0    1
r1    2
r2    3
r3    0
r4    0
Name: c0, dtype: int64

In [11]:
# 행인덱스 초기화

import pandas as pd

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=["r0", "r1", "r2"])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [13]:
ndf = df.reset_index()
print(df)
print()
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [15]:
ndf2 = df.reset_index(names=["c00"])
print(ndf2)

  c00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [16]:
ndf3 = df.reset_index(drop=True)
print(ndf3)

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [19]:
# 행인덱스를 기준으로 데이터 프레임 정렬
# sort_index()
# DF객체.sort_index()

import pandas as pd

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=["r0", "r2", "r1"])
print(df)
print()

ndf = df.sort_index()
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [ ]:
# 인덱스 오름차순/내림차순 정렬

ndf2 = df.sort_index(ascending=False)
print(ndf2)
print()

ndf3 = df.sort_index(ascending=True)
print(ndf3)

    c0  c1  c2  c3  c4
r2   2   5   8  11  14
r1   3   6   9  12  15
r0   1   4   7  10  13

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [23]:
# 열기준 정렬
# DF객체.sort_values()

import pandas as pd

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=["r0", "r1", "r2"])
print(df)
print()

ndf = df.sort_values(by="c2", ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [24]:
ndf2 = df.sort_values(by=["c3", "c4"], ascending=[False, True])
print(ndf2)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [ ]:
import pandas as pd

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 11],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=["r0", "r1", "r2"])

ndf2 = df.sort_values(by=["c3", "c4"], ascending=[False, True])
print(ndf2)

# c3에 중복값이 있을 경우 c4를 기준으로 정렬

    c0  c1  c2  c3  c4
r1   2   5   8  11  14
r2   3   6   9  11  15
r0   1   4   7  10  13

In [26]:
###