In [32]:
# 시리즈 연산

import pandas as pd

dict_data = {
    "국어" : 100,
    "영어" : 80,
    "수학" : 90
}
student1 = pd.Series(dict_data)
print(student1)
print()

percentage = student1 / 200
print(percentage)
print()
print(type(percentage))

국어    100
영어     80
수학     90
dtype: int64

국어    0.50
영어    0.40
수학    0.45
dtype: float64

<class 'pandas.Series'>

In [33]:
p2 = student1 * 0.5
print(p2)

국어    50.0
영어    40.0
수학    45.0
dtype: float64

In [34]:
p3 = student1 + 50
print(p3)

국어    150
영어    130
수학    140
dtype: int64

In [35]:
# 시리즈와 시리즈 연산

import pandas as pd

dict_data1 = {
    "국어" : 100,
    "영어" : 80,
    "수학" : 90
}

dict_data2 = {
    "수학" : 80,
    "국어" : 90,
    "영어" : 80
}

student1 = pd.Series(dict_data1)
student2 = pd.Series(dict_data2)

print(student1)
print()
print(student2)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

In [36]:
addition = student1 + student2
print(type(addition))
print()
print(addition)

<class 'pandas.Series'>

국어    190
수학    170
영어    160
dtype: int64

In [37]:
substraction = student1 - student2
print(type(substraction))
print()
print(substraction)

<class 'pandas.Series'>

국어    10
수학    10
영어     0
dtype: int64

In [38]:
multiplication = student1 * student2
print(type(multiplication))
print()
print(multiplication)

<class 'pandas.Series'>

국어    9000
수학    7200
영어    6400
dtype: int64

In [39]:
division = student1 / student2
print(type(division))
print()
print(division)

<class 'pandas.Series'>

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [40]:
lis = [addition, substraction, multiplication, division]
df_index = ["덧셈", "뺄셈", "곱셈", "나눗셈"]

result = pd.DataFrame(lis, index=df_index)
result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [41]:
# NaN 값이 있는 시리즈 연산

import pandas as pd
import numpy as np

dict_data1 = {
    "국어" : np.nan,
    "영어" : 80,
    "수학" : 90
}

dict_data2 = {
    "수학" : 80,
    "국어" : 90
}

student1 = pd.Series(dict_data1)
student2 = pd.Series(dict_data2)

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [42]:
addition = student1 + student2
print(addition)

국어      NaN
수학    170.0
영어      NaN
dtype: float64

In [43]:
substraction = student1 - student2
print(substraction)

국어     NaN
수학    10.0
영어     NaN
dtype: float64

In [44]:
multiplication = student1 * student2
print(multiplication)

국어       NaN
수학    7200.0
영어       NaN
dtype: float64

In [45]:
division = student1 / student2
print(division)

국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [46]:
result = pd.DataFrame([addition, substraction, multiplication, division], index=df_index)
result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [47]:
# 연산메서드

import pandas as pd
import numpy as np

dict_data1 = {
    "국어" : np.nan,
    "영어" : 80,
    "수학" : 90
}

dict_data2 = {
    "수학" : 80,
    "국어" : 90
}

student1 = pd.Series(dict_data1)
student2 = pd.Series(dict_data2)

sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

lis = [sr_add, sr_sub, sr_mul, sr_div]

result = pd.DataFrame(lis, index=df_index)
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [48]:
# !pip install seaborn      -> ! : 터미널에서 실행

In [49]:
# 데이터프레임 연산
# 데이터프레임과 숫자 연산

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [50]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [52]:
titanic.shape

(891, 15)

In [58]:
df = titanic.loc[:, ["age", "fare"]]
print(df.head(6))
print()
print(df.shape)
print()
print(type(df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583

(891, 2)

<class 'pandas.DataFrame'>

In [57]:
df.head(10)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [59]:
addition = df + 10
print(addition.head(10))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500
5   NaN  18.4583
6  64.0  61.8625
7  12.0  31.0750
8  37.0  21.1333
9  24.0  40.0708

In [63]:
# 데이터프레임과 데이터프레임 연산

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "fare"]]

df.tail(10)

      age     fare
881  33.0   7.8958
882  22.0  10.5167
883  28.0  10.5000
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

In [64]:
addition = df + 10
addition.tail(10)

      age     fare
881  43.0  17.8958
882  32.0  20.5167
883  38.0  20.5000
884  35.0  17.0500
885  49.0  39.1250
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

In [66]:
substraction = addition - df
substraction.tail(10)
type(substraction)

pandas.DataFrame

In [71]:
sample1 = addition.tail(10)
print(sample1.shape)
print()
print(sample1)

(10, 2)

      age     fare
881  43.0  17.8958
882  32.0  20.5167
883  38.0  20.5000
884  35.0  17.0500
885  49.0  39.1250
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

In [73]:
sample2 = substraction.tail(10).fillna(0)
print(sample2.shape)
print()
print(sample2)

(10, 2)

      age  fare
881  10.0  10.0
882  10.0  10.0
883  10.0  10.0
884  10.0  10.0
885  10.0  10.0
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [74]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)

print(df_add)
print()
print(df_sub)
print()
print(df_mul)
print()
print(df_div)

      age     fare
881  53.0  27.8958
882  42.0  30.5167
883  48.0  30.5000
884  45.0  27.0500
885  59.0  49.1250
886  47.0  33.0000
887  39.0  50.0000
888   0.0  43.4500
889  46.0  50.0000
890  52.0  27.7500

      age     fare
881  33.0   7.8958
882  22.0  10.5167
883  28.0  10.5000
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
888   0.0  23.4500
889  26.0  30.0000
890  32.0   7.7500

       age     fare
881  430.0  178.958
882  320.0  205.167
883  380.0  205.000
884  350.0  170.500
885  490.0  391.250
886  370.0  230.000
887  290.0  400.000
888    0.0  334.500
889  360.0  400.000
890  420.0  177.500

     age     fare
881  4.3  1.78958
882  3.2  2.05167
883  3.8  2.05000
884  3.5  1.70500
885  4.9  3.91250
886  3.7  2.30000
887  2.9  4.00000
888  NaN  3.34500
889  3.6  4.00000
890  4.2  1.77500

In [75]:
####