In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv('./data/auto-mpg.csv', header=None)
df.columns = [
    "mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"
]

df['horsepower'] = df['horsepower'].replace('?', np.nan)
df = df.dropna(subset=['horsepower'], axis=0)
df['horsepower'] = df['horsepower'].astype('float')

df["horsepower"].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [23]:
df["horsepower_minmax"] = (df["horsepower"] - df["horsepower"].min()) / (df["horsepower"].max() - df["horsepower"].min())
df[["horsepower", 'horsepower_minmax']].head(10)

   horsepower  horsepower_minmax
0       130.0           0.456522
1       165.0           0.646739
2       150.0           0.565217
3       150.0           0.565217
4       140.0           0.510870
5       198.0           0.826087
6       220.0           0.945652
7       215.0           0.918478
8       225.0           0.972826
9       190.0           0.782609

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['horsepower_minmax2'] = scaler.fit_transform(df[['horsepower']])
df[['horsepower', 'horsepower_minmax', 'horsepower_minmax2']].head(10)

   horsepower  horsepower_minmax  horsepower_minmax2
0       130.0           0.456522            0.456522
1       165.0           0.646739            0.646739
2       150.0           0.565217            0.565217
3       150.0           0.565217            0.565217
4       140.0           0.510870            0.510870
5       198.0           0.826087            0.826087
6       220.0           0.945652            0.945652
7       215.0           0.918478            0.918478
8       225.0           0.972826            0.972826
9       190.0           0.782609            0.782609

In [25]:
# standardscaler -> 평균 0, 표준편차 1인 정규분포

df['horsepower_standard'] = (df['horsepower'] - df["horsepower"].mean()) / (df["horsepower"].std())
print(df['horsepower_standard'].head(10))

0    0.663285
1    1.572585
2    1.182885
3    1.182885
4    0.923085
5    2.429924
6    3.001484
7    2.871584
8    3.131384
9    2.222085
Name: horsepower_standard, dtype: float64

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['horsepower_standard2'] = scaler.fit_transform(df[['horsepower']])
df[['horsepower', 'horsepower_standard', 'horsepower_standard2']].head(10)

   horsepower  horsepower_standard  horsepower_standard2
0       130.0             0.663285              0.664133
1       165.0             1.572585              1.574594
2       150.0             1.182885              1.184397
3       150.0             1.182885              1.184397
4       140.0             0.923085              0.924265
5       198.0             2.429924              2.433030
6       220.0             3.001484              3.005320
7       215.0             2.871584              2.875254
8       225.0             3.131384              3.135386
9       190.0             2.222085              2.224924

In [27]:
##