In [57]:
# 문자열을 타임 스탬프로 변환

import pandas as pd

df = pd.read_csv('./data/stock-data.csv')

print(df.head())
print()
print(df.info())
print()
print(df.describe())

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB
None

              Close         Start          High           Low         Volume
count     20.000000     20.000000     20.000000     20.000000      20.000000
mean   11662.500000  11755.000000  12015.000000  11374.500000  158014.150000
std      927.060294    865.250192    907.729962    884.369981  134473.512003
min    10100.000000  10550.000000  10900.000000   9990.000000   25171.000000
25%    11087.500000  11125.000000  11350.000000  10737.500000   58323.250000
50%    11725.000000  11800.000000  12025.000000  11500.000000  134176.500000
75%    11962.500000  12050.000000  12262.500000  11912.500000  185836.000000
max    13450.000000  13600.000000  13700.000000  13150.000000  558148.000000

In [58]:
df['new_Date'] = pd.to_datetime(df['Date'])

print(df.head(10))
print()
print(df.info())
print()
print(type(df['new_Date'][0]))

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26
5  2018-06-25  11150  11400  11450  11000   55519 2018-06-25
6  2018-06-22  11300  11250  11450  10750  134805 2018-06-22
7  2018-06-21  11200  11350  11750  11200  133002 2018-06-21
8  2018-06-20  11550  11200  11600  10900  308596 2018-06-20
9  2018-06-19  11300  11850  11950  11300  180656 2018-06-19

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB
None

<class 'pandas.Timestamp'>

In [59]:
df = df.set_index('new_Date')
df = df.drop('Date', axis=1)

print(df.head())

            Close  Start   High    Low  Volume
new_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [60]:
pd.DatetimeIndex(['2022-12-25', '2023/01/25'])

DatetimeIndex(['2022-12-25', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [61]:
pd.Timestamp('2023-12-25')

Timestamp('2023-12-25 00:00:00')

In [62]:
pd.to_datetime("2023년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2023-12-25 00:00:00')

In [63]:
pd.to_datetime("12-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2023-12-12 23:59:59')

In [64]:
import pandas as pd

dates = ['2019-01-01', '2020-03-01', '2026-06-01']

ts_dates = pd.to_datetime(dates)
print(ts_dates)

DatetimeIndex(['2019-01-01', '2020-03-01', '2026-06-01'], dtype='datetime64[us]', freq=None)

In [65]:
pr_day = ts_dates.to_period(freq='D')
pr_month = ts_dates.to_period(freq='M')
pr_year = ts_dates.to_period(freq='Y')
print(f"{pr_day}\n{pr_month}\n{pr_year}")

PeriodIndex(['2019-01-01', '2020-03-01', '2026-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2026-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2026'], dtype='period[Y-DEC]')

In [66]:
# 시계열 데이터 만들기

import pandas as pd

ts_ms = pd.date_range(
    start='2024-01-01',
    end=None,
    periods=6,
    freq='MS',
    tz='Asia/Seoul'
)
print(ts_ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [67]:
ts_me = pd.date_range(
    start='2024-01-01',
    end=None,
    periods=6,
    freq='ME',
    tz='Asia/Seoul'
)
print(ts_me)

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [68]:
ts_3ms = pd.date_range(
    start='2024-01-01',
    end=None,
    periods=6,
    freq='3MS',
    tz='Asia/Seoul'
)
print(ts_3ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [69]:
pr_m = pd.period_range(
    start='2024-01-01',
    end=None,
    periods=3,
    freq="M"
)
print(pr_m)

PeriodIndex(['2024-01', '2024-02', '2024-03'], dtype='period[M]')

In [70]:
pr_h = pd.period_range(
    start='2024-01-01',
    end=None,
    periods=3,
    freq="h"
)
print(pr_h)

PeriodIndex(['2024-01-01 00:00', '2024-01-01 01:00', '2024-01-01 02:00'], dtype='period[h]')

In [71]:
# 시계열 데이터 활용
# 날짜 데이터 분리

df = pd.read_csv('./data/stock-data.csv')
df['new_Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['new_Date'].dt.year
df['Month'] = df['new_Date'].dt.month
df['Day'] = df['new_Date'].dt.day

df['Date_m'] = df['new_Date'].dt.to_period(freq='M')
df.head()

,Date,Close,Start,High,Low,Volume,new_Date,Year,Month,Day,Date_m
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,7,2,2018-07
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018-06

In [72]:
# 시간 인덱스 활용

df = pd.read_csv('./data/stock-data.csv')
df['new_Date'] = pd.to_datetime(df['Date'])

df = df.set_index('new_Date').sort_index()
print(df.head(10))

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-18  2018-06-18  12000  13400  13400  12000  309787

In [73]:
df.loc['2018-06-27']

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [74]:
df[df.index < '2018-06-05']

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [75]:
# 시계열 변환

df = pd.read_csv('./data/stock-data.csv')
df['new_Date'] = pd.to_datetime(df['Date'])
df = df.drop('Date', axis=1)
df = df.set_index('new_Date').sort_index()
ts = df.head(10)
ts.shift(1)

              Close    Start     High      Low    Volume
new_Date
2018-06-01      NaN      NaN      NaN      NaN       NaN
2018-06-04  11900.0  11800.0  12100.0  11750.0   32062.0
2018-06-05  11900.0  11900.0  12200.0  11700.0   25171.0
2018-06-07  12150.0  11800.0  12250.0  11800.0   42485.0
2018-06-08  11950.0  12200.0  12300.0  11900.0   49088.0
2018-06-11  11950.0  11950.0  12200.0  11800.0   59258.0
2018-06-12  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-14  13200.0  12200.0  13300.0  12050.0  558148.0
2018-06-15  13450.0  13200.0  13700.0  13150.0  347451.0
2018-06-18  13400.0  13600.0  13600.0  12900.0  201376.0

In [76]:
ts.shift(-2)

              Close    Start     High      Low    Volume
new_Date
2018-06-01  12150.0  11800.0  12250.0  11800.0   42485.0
2018-06-04  11950.0  12200.0  12300.0  11900.0   49088.0
2018-06-05  11950.0  11950.0  12200.0  11800.0   59258.0
2018-06-07  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-08  13200.0  12200.0  13300.0  12050.0  558148.0
2018-06-11  13450.0  13200.0  13700.0  13150.0  347451.0
2018-06-12  13400.0  13600.0  13600.0  12900.0  201376.0
2018-06-14  12000.0  13400.0  13400.0  12000.0  309787.0
2018-06-15      NaN      NaN      NaN      NaN       NaN
2018-06-18      NaN      NaN      NaN      NaN       NaN